version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./www/html:/var/www/html
    depends_on:
      - php
 
  php:
    build: ./php
    volumes:
      - ./www/html:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - db
 
  db:
    image: mysql:latest
    ports:
      - 13306:3306
    volumes:
      # - ./mysql/data/:/var/lib/mysql
      - ./mysql/data:/var/lib/mysql
      - ./mysql/sql:/docker-entrypoint-initdb.d
      - ./mysql/my.conf:/etc/mysql/conf.d
      


    environment:
      MYSQL_DATABASE: first
      MYSQL_USER: dondon
      MYSQL_PASSWORD: mymy
      MYSQL_ROOT_PASSWORD: mymy
 
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8888:80
    depends_on:
      - db

# データベースとユーザーを記述